// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SmokeTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logincheckingusername() {
    driver.get("https://shop.demoqa.com//");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Muamer.dzanko");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Pa55word12345?");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector(".custom-logo:nth-child(1)")).click();
  }
  @Test
  public void logincheckingemail() {
    driver.get("https://shop.demoqa.com//");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Muamer.dzanko@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Pa55word12345?");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector(".custom-logo:nth-child(1)")).click();
  }
  @Test
  public void logInBlankNegativetest() {
    driver.get("https://shop.demoqa.com/");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector(".woocommerce-error > li")).click();
    driver.findElement(By.cssSelector(".custom-logo:nth-child(1)")).click();
  }
  @Test
  public void negativeaddingtocarttest() {
    driver.get("https://shop.demoqa.com/");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.cssSelector(".cart-name-and-total")).click();
    driver.findElement(By.cssSelector(".wc-backward")).click();
    driver.findElement(By.cssSelector(".noo-product-item:nth-child(1) .owl-item:nth-child(1) .product-one-thumb")).click();
    driver.findElement(By.id("pa_color")).click();
    driver.findElement(By.cssSelector(".single_add_to_cart_button")).click();
    assertThat(driver.switchTo().alert().getText(), is("Please select some product options before adding this product to your cart."));
    driver.findElement(By.cssSelector(".custom-logo:nth-child(1)")).click();
  }
  @Test
  public void orderingandcheckoutautomatedtest() {
    driver.get("https://shop.demoqa.com/");
    driver.manage().window().setSize(new Dimension(1024, 768));
    driver.findElement(By.linkText("Dismiss")).click();
    driver.findElement(By.cssSelector(".cart-name-and-total")).click();
    driver.findElement(By.cssSelector(".wc-backward")).click();
    driver.findElement(By.cssSelector(".noo-product-item:nth-child(1) .owl-item:nth-child(1) .product-one-thumb")).click();
    driver.findElement(By.id("pa_color")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pa_color"));
      dropdown.findElement(By.xpath("//option[. = 'Beige']")).click();
    }
    driver.findElement(By.id("pa_size")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pa_size"));
      dropdown.findElement(By.xpath("//option[. = 'Large']")).click();
    }
    driver.findElement(By.cssSelector(".icon_plus")).click();
    driver.findElement(By.cssSelector(".single_add_to_cart_button")).click();
    driver.findElement(By.cssSelector(".cart-name-and-total")).click();
    driver.findElement(By.cssSelector(".alt")).click();
    driver.findElement(By.id("billing_first_name")).click();
    driver.findElement(By.id("billing_first_name")).sendKeys("Muamer");
    driver.findElement(By.id("billing_last_name")).click();
    driver.findElement(By.id("billing_last_name")).sendKeys("Dzanko");
    driver.findElement(By.id("billing_company")).click();
    driver.findElement(By.id("billing_company")).sendKeys("Company123");
    driver.findElement(By.id("select2-billing_country-container")).click();
    js.executeScript("window.scrollTo(0,514)");
    driver.findElement(By.id("billing_address_1")).click();
    driver.findElement(By.id("billing_address_1")).sendKeys("Safeta Isovica 17");
    driver.findElement(By.id("billing_address_2")).click();
    driver.findElement(By.id("billing_address_2")).sendKeys("2 sprat");
    driver.findElement(By.id("billing_postcode")).click();
    driver.findElement(By.id("billing_postcode")).sendKeys("71000");
    driver.findElement(By.id("billing_city")).click();
    driver.findElement(By.id("billing_city")).sendKeys("Sarajevo");
    driver.findElement(By.id("billing_phone")).click();
    driver.findElement(By.id("billing_phone")).sendKeys("38762839832");
    driver.findElement(By.id("billing_email")).click();
    driver.findElement(By.id("billing_email")).sendKeys("muamer.dzanko@gmail.com");
    driver.findElement(By.id("terms")).click();
    driver.findElement(By.id("place_order")).click();
    driver.findElement(By.cssSelector(".custom-logo:nth-child(1)")).click();
  }
}
